apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b0hp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-b0hp
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-b0hp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b0hp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b0hp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fhba-tenant/quarkus/devfile-sample-code-with-quarkus-b0hp@sha256:88a3ff8a54f739dccc327659bdb75a7c98e392d101e5da797ee0fb2ed77dbbf9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
